version: '3.8'

services:
  database:
    container_name: testing-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
